window.env = {
  REACT_APP_TITLE: "$APP_TITLE",
  REACT_APP_DESCRIPTION_CONTENT: "$DESCRIPTION",
  REACT_APP_API_BASE_URL: "$API_BASE_URL",
  REACT_APP_FRONT_URL: "$FRONT_URL",
  REACT_APP_CLIENT_ID: "$CLIENT_ID",
  REACT_APP_SUPERSET_URL:"$SUPERSET_URL",
  REACT_APP_CLIENT_SECRET: "$CLIENT_SECRET",
};
